### ISSUE TITLE
[Request] Any Plans on porting Kali Nethunter?

### ISSUE THREAD

**Issue by LucaBongiorni** [deltaxflux/flux#12]

**Comment by deltaxflux** [comment]
Today, we don't have any plans. But  it should be possible.  However there are many dependencies

**Comment by strasharo** [comment]
I don't have access to Nethunter-compatible hardware yet, but could give it a go if I manage to find a friend to borrow one from. Does Nethunter rely on the built in wireless adapter to perform injection or folks are attaching external USB wireless adapters via OTG?

**Comment by deltaxflux** [comment]
Yes you can use external wireless adapters over usb (OTG) but this only works i guess on nexus and oneplus devices. I tried it on LG but it won´t work. However will not develop a compatible flashable version because, i don´t now how. I´m only a developer for Shell script & batch script. I now how to attack wireless devices, use metaploit... Futhermore i´m not the right person for android apps / flashable zips / kernels. Maby we find developers...

**Comment by LucaBongiorni** [comment]
FYI Just pust flux in my TODO list.
As soon I have time I'll try to install it on my OP2.

**Comment by deltaxflux** [comment]
Yes I had success with flashing the nethunter zip,  for more details look at the xda post

**Comment by arshiay** [comment]
In lg devices you need ogt Y cable to power up external wifi modem
Because lg does not support power on otg
