### ISSUE TITLE
dhcpd fails to start if the lease file is not present already

### ISSUE THREAD

**Issue by strasharo** [deltaxflux/flux#5]
If the lease file is not present when dhcpd starts, it just silently terminates. Touching /var/lib/dhcp/dhcpd.leases in advance resolves the issue, so I guess it will be good if the lease file is being touched by the script prior starting dhcpd.

**Comment by deltaxflux** [comment]
Hello can you help me to solve the Bug, because i can´t find the mistake. 
However the file is located in /etc/dhcpd.conf. and var/lib/dhcp 
so we should decide. 
1.) We can create a dhcp config file and mv it to the location (which is located in the flux folder)
or 
2.) We the Script will create a config file which we move in the dhcp folder (Recommented) 
You are Calloborator so cp fluxion and we will create a folder for tests hopefully we find a solutuion

**Comment by strasharo** [comment]
The issue comes from this:
http://linux.die.net/man/5/dhcpd.leases

> When dhcpd is first installed, there is no lease database. However, dhcpd requires that a lease database be present before it will start. To make the initial lease database, just create an empty file called /var/lib/dhcpd/dhcpd.leases. You can do this with:
> 
>     touch /var/lib/dhcpd/dhcpd.leases
> 

So instead of relying on the system global leases file, I redirected dhcpd to a local copy, created in the dump path. That way we are ensuring that the file is present and we're not relying on external files for it.
